config:
  backup: true
  banner: false
  create: true
  dotpath: ~/Documents/SCM/GitHub/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_flameshot.ini:
    src: config/flameshot/flameshot.ini
    dst: ~/.config/flameshot/flameshot.ini
  f_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  d_pictures:
    src: config/pictures
    dst: ~/.config/pictures
  f_aliases.zsh:
    src: config/zsh/aliases.zsh
    dst: ~/.config/zsh/aliases.zsh
  f_completion.zsh:
    src: config/zsh/completion.zsh
    dst: ~/.config/zsh/completion.zsh
  f_environment.zsh:
    src: config/zsh/environment.zsh
    dst: ~/.config/zsh/environment.zsh
  f_options.zsh:
    src: config/zsh/options.zsh
    dst: ~/.config/zsh/options.zsh
  f_private.zsh:
    src: config/zsh/private.zsh
    dst: ~/.config/zsh/private.zsh
  f_prompt.zsh:
    src: config/zsh/prompt.zsh
    dst: ~/.config/zsh/prompt.zsh
  f_zshrc:
    src: config/zsh/zshrc
    dst: ~/.zshrc
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xserverrc:
    src: xserverrc
    dst: ~/.xserverrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_work_gitconfig:
    src: work/gitconfig
    dst: ~/.gitconfig
  f_gitconfig_common:
    src: config/git/gitconfig.common
    dst: ~/.config/git/gitconfig.common
  d_autorandr:
    src: config/autorandr
    dst: ~/.config/autorandr
  d_work_autorandr:
    src: work/config/autorandr
    dst: ~/.config/autorandr
    chmod: '755'
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_themes:
    src: themes
    dst: ~/.themes
  f_alacritty.toml:
    src: config/alacritty/alacritty.toml
    dst: ~/.config/alacritty/alacritty.toml
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
profiles:
  olive:
    dotfiles:
    - f_dunstrc
    - f_flameshot.ini
    - f_settings.ini
    - f_config
    - f_i3status_config
    - d_pictures
    - f_aliases.zsh
    - f_completion.zsh
    - f_environment.zsh
    - f_options.zsh
    - f_private.zsh
    - f_prompt.zsh
    - f_zshrc
    - f_ssh_config
    - f_xinitrc
    - f_xserverrc
    - f_gitconfig
    - f_gitconfig_common
    - d_autorandr
    - d_nvim
    - d_themes
    - f_alacritty.toml
    - d_tmux
  oak:
    dotfiles:
    - f_dunstrc
    - f_config
    - f_i3status_config
    - d_pictures
    - f_aliases.zsh
    - f_completion.zsh
    - f_environment.zsh
    - f_options.zsh
    - f_private.zsh
    - f_prompt.zsh
    - f_zshrc
    - f_work_gitconfig
    - f_gitconfig_common
    - d_work_autorandr
    - d_nvim
    - f_alacritty.toml
    - d_tmux

