dynvariables:
  user: test -n "$SUDO_USER" && echo $SUDO_USER || echo $USER 
config:
  backup: true
  banner: false
  create: true
  dotpath: /home/{{@@ user @@}}/.dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_grub:
    src: config/grub/grub
    dst: /etc/default/grub
profiles:
  debian:
    dotfiles:
    - f_grub
