config:
  backup: true
  banner: false
  create: true
  dotpath: ~/Documents/SCM/GitHub/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
profiles:
  olive:
    dotfiles:
