config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_gitconfig:
    src: config/git/gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
    upignore:
    - '*/gitconfig'
    - '*/*.custom'
    instignore:
    - '*/gitconfig'
    - '*/*.custom'
    cmpignore:
    - '*/gitconfig'
    - '*/*.custom'
  f_bashrc:
    src: config/bash/bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: config/bash/bash_profile
    dst: ~/.bash_profile
    chmod: '644'
  d_bash:
    src: config/bash
    dst: ~/.config/bash
    upignore:
    - '*/bashrc'
    - '*/omb-bashrc'
    - '*/bash_profile'
    - '*/share/*'
    instignore:
    - '*/bashrc'
    - '*/omb-bashrc'
    - '*/bash_profile'
    - '*/share/*'
    cmpignore:
    - '*/bashrc'
    - '*/omb-bashrc'
    - '*/bash_profile'
    - '*/share/*'
  f_omb_bashrc:
    src: config/bash/omb-bashrc
    dst: ~/.config/bash/share/oh-my-bash/bashrc
    chmod: '644'
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_klipperrc:
    src: config/klipper/klipperrc
    dst: ~/.config/klipperrc
    chmod: '600'
  d_konsole:
    src: config/konsole
    dst: ~/.local/share/konsole
    upignore:
    - '*/konsolerc'
    instignore:
    - '*/konsolerc'
    cmpignore:
    - '*/konsolerc'
  f_konsolerc:
    src: config/konsole/konsolerc
    dst: ~/.config/konsolerc
  f_kdeglobals:
    src: config/kdeglobals
    dst: ~/.config/kdeglobals
    chmod: '600'
  f_plasmarc:
    src: config/plasmarc
    dst: ~/.config/plasmarc
    chmod: '600'
  f_plasmashellrc:
    src: config/plasmashellrc
    dst: ~/.config/plasmashellrc
    chmod: '600'
  f_kglobalshortcutsrc:
    src: config/kglobalshortcutsrc
    dst: ~/.config/kglobalshortcutsrc
    chmod: '600'
  f_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
    chmod: '600'
  f_gtk-4.0_settings.ini:
    src: config/gtk-4.0/settings.ini
    dst: ~/.config/gtk-4.0/settings.ini
    chmod: '600'
  d_plasma_desktoptheme:
    src: config/plasma/desktoptheme
    dst: ~/.local/share/plasma/desktoptheme
  d_color_schemes:
    src: config/color-schemes
    dst: ~/.local/share/color-schemes
  d_aurorae_themes:
    src: config/aurorae/themes
    dst: ~/.local/share/aurorae/themes
  f_kwinrc:
    src: config/kwinrc
    dst: ~/.config/kwinrc
    chmod: '600'
  d_ghostty:
    src: config/ghostty
    dst: ~/.config/ghostty
profiles:
  debian:
    dotfiles:
    - f_gitconfig
    - d_git
    - f_bashrc
    - f_bash_profile
    - d_bash
    - f_omb_bashrc
    - f_tmux.conf
    - d_nvim
    - f_klipperrc
    - d_konsole
    - f_konsolerc
    - f_kdeglobals
    - f_plasmarc
    - f_plasmashellrc
    - f_kglobalshortcutsrc
    - f_settings.ini
    - f_gtk-4.0_settings.ini
    - d_plasma_desktoptheme
    - d_color_schemes
    - d_aurorae_themes
    - f_kwinrc
  ZAG1X00018.local:
    dotfiles:
    - f_gitconfig
    - d_git
    - f_bashrc
    - f_bash_profile
    - d_bash
    - f_omb_bashrc
    - f_tmux.conf
    - d_nvim
    - d_ghostty
