alias ll="ls -AlGh --color=always"
alias make="make --no-print-directory"
alias valgrind-leak="valgrind --leak-check=full --show-leak-kinds=all --leak-resolution=high --track-origins=yes --read-var-info=yes --child-silent-after-fork=yes"
alias dotdrop="dotdrop --cfg=${DOTREPO}/config/dotdrop/config.yaml"
alias dotgit="git -C ${DOTREPO}"
alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"