return {
    {
        'nvim-treesitter/nvim-treesitter',
        branch = 'master',
        lazy = false,
        build = ":TSUpdate",
        config = function()
            local configs = require('nvim-treesitter.configs')
            configs.setup({
                modules = {},
                sync_install = false,
                ignore_install = {},
                auto_install = false,
                highligh = { enable = true },
                indent = { enable = true },
                autotage = { enable = true },
                ensure_installed = {
                    "arduino",
                    "awk",
                    "bash",
                    "bitbake",
                    "c",
                    "cmake",
                    "cpp",
                    "csv",
                    "desktop",
                    "devicetree",
                    "diff",
                    "disassembly",
                    "dockerfile",
                    "dot",
                    "doxygen",
                    "dtd",
                    "git_rebase",
                    "gitattributes",
                    "gitcommit",
                    "gitignore",
                    "ini",
                    "jq",
                    "json",
                    "kconfig",
                    "linkerscript",
                    "lua",
                    "make",
                    "markdown",
                    "markdown_inline",
                    "objdump",
                    "python",
                    "regex",
                    "query",
                    "rst",
                    "rust",
                    "ssh_config",
                    "tmux",
                    "toml",
                    "udev",
                    "vim",
                    "vimdoc",
                    "xml",
                    "yaml",
                },
            })
        end
    },
}
