vim.opt.backup = false                                  -- do not create a backup file
vim.opt.clipboard = "unnamedplus"                       -- allows neovim to access the system clipboard
vim.opt.cmdheight = 2                                   -- more space for the neovim command line for displaying messages
vim.opt.complete = ""                                   -- clear because nvim-cmp is used
vim.opt.completeopt = {}                                -- mosly just for cmp
vim.opt.conceallevel = 0                                -- so that `` is visible in markdown files
vim.opt.fileencoding = "utf-8"                          -- the encoding written to a file
vim.opt.incsearch = true                                -- search as you type
vim.opt.hlsearch = true                                 -- highlight all search matches on previous search
vim.opt.ignorecase = true                               -- ignore case in search patterns
vim.opt.mouse = "a"                                     -- allow the mous to be used in neovim
vim.opt.pumheight = 10                                  -- pop up menu height
vim.opt.showmode = false                                -- do not display the current neovim mode, have different means to that
vim.opt.showtabline = 2                                 -- always show tabs
vim.opt.smartcase = true                                -- smart case
vim.opt.smartindent = true                              -- make indenting smarter again
vim.opt.splitbelow = true                               -- force all horizontal splits to go bellow current window
vim.opt.splitright = true                               -- force all vertical splits to go to the right of current window
vim.opt.swapfile = false                                -- do not create a swap file
vim.opt.termguicolors = true                            -- set terminal gui colors (most terminals support this)
vim.opt.timeoutlen = 1000                               -- time to wait for a mapped sequence to complete (in miliseconds)
vim.opt.undofile = true                                 -- enable persistant undo
vim.opt.undodir = os.getenv("HOME") .. "/.nvim/undodir" -- directory used for storing data for undo
vim.opt.updatetime = 50                                 -- faster completition (4000ms default)
vim.opt.writebackup = false                             -- if a file is being edited by another program
vim.opt.expandtab = true                                -- convert tabs to spaces
vim.opt.shiftwidth = 4                                  -- the number of spaces inserted for each indentation
vim.opt.tabstop = 4                                     -- insert 4 spaces for a tab
vim.opt.softtabstop = 4                                 -- characters the cursor moves when tab is pressed
vim.opt.cursorline = true                               -- highlight the current line
vim.opt.number = true                                   -- set numbered lines
vim.opt.relativenumber = true                           -- set relative numbered lines
vim.opt.numberwidth = 2                                 -- set number column width (4 default)
vim.opt.signcolumn = "yes"                              -- always show the sign column
vim.opt.wrap = false                                    -- do not break a line
vim.opt.scrolloff = 8                                   -- number of lines visible around the cursor line
vim.opt.guifont = "Sauce Code Nerd Font:10"             -- font used in graphical neovim applications
